src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

SSH CBC modes are highly insecure: https://www.kb.cert.org/vuls/id/958563
Every modern implementation of SSH supports AES128-CTR, so I think it's wise to use only it.
https://issues.jenkins-ci.org/browse/JENKINS-39805

[JENKINS-39805] - Drop CBC: https://www.kb.cert.org/vuls/id/958563

---

pom.xml
src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

This solves a really bad issue where 1 handshake
in 256 fails randomly [1].
Note: The issue was easily reproducable, and after this
dependency upgrade the handshake did not fail in over
15K test connections.
[1] https://issues.apache.org/jira/browse/SSHD-330

[FIXED JENKINS-40362] Upgrads sshd-core to 0.14.0 to pick SSHD-330

---

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

Same as #11 but _without_ the dependency on #10, to see if this can be used from https://github.com/jenkinsci/jenkins/pull/2795.
@reviewbybees @jenkinsci/code-reviewers

[JENKINS-33595] Disable SSHD port by default on new installations

---

pom.xml
src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java
src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
src/main/java/org/jenkinsci/main/modules/sshd/UserAuthNamedFactory.java

Helpful, if not strictly required, for https://github.com/jenkinsci/jenkins/pull/2795. Cf. #8.
Note that `sshd-core` is not compatible across the 1.0 boundary (hence the `src/main/java/` changes), but
* It should not matter for typical plugins since the only extension point from Jenkins is `SshCommandFactory`, which is only referring to `Command`, which does not seem to have changed in interface (including its transitive dependencies) since 0.x.
* `cloudbees-ssh-slaves` uses 0.13.0 and would not compile against 1.x, but it declares an explicit dependency and uses `pluginFirstClassLoader`.
* `ssh-agent` uses 1.0 and `pluginFirstClassLoader`.
* `remote-terminal-access` uses Jenkins’ version and will not work with 1.x, but only in the commands that would be broken by …

Updating sshd-core to 1.4.0

---

pom.xml
src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java

[JENKINS-43610] Move to latest version of ssh-cli-auth to remove Trilead references from SSHD module

[JENKINS-43668] - Remove Trilead references

---

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
src/test/java/org/jenkinsci/main/modules/sshd/SSHDTest.java

If the JVM supports unlimited-strength encryption, we can enable more ciphers.
And the new SSHD core version provides good API for it.
CBC ciphers won't be added due to https://www.kb.cert.org/vuls/id/958563 . So it is not exactly what has been requested in [JENKINS-39738](https://issues.jenkins-ci.org/browse/JENKINS-39738) though I think it is a reasonable fix. 
@reviewbybees @jglick + @johnou @chillum since it was raised in https://github.com/jenkinsci/sshd-module/pull/5#discussion_r88207121

[FIXED JENKINS-39738] - Enable aes192ctr and aes256ctr ciphers if JVM supports them

---

pom.xml

This version picks the release with EdDSA 1.2. It unblocks merging of SSHD into the core, which was not possible due to the binary conflict between EdDSA 1.2 in Trilead-SSH2 and EdDSA 1.1 in SSHD. See https://github.com/jenkinsci/jenkins/pull/2853 and https://github.com/jenkinsci/jenkins/pull/2848 for more info
Changelogs:
* 1.5.0 has been burned 
* [SSHD 1.6.0](https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12340583&styleName=&projectId=12310849&Create=Create&atl_token=A5KQ-2QAV-T4JA-FDED%7C1ba4a61d9aff8c9b2113db16bd22472cf1334e04%7Clout)
Full diff: https://github.com/apache/mina-sshd/compare/sshd-1.4.0...sshd-1.6.0
@reviewbybees @paladox @mc1arke

Update to SSHD 1.6.0

---

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

- Fix race condition in `SSHD.start()`.
- Do not let Jenkins to wait until `SSHD` is fully up.
- I have seen launch stuck for minutes while running parallel `jenkins-test-harness` tests as it was waiting for system entropy to launch a service I do not care for on the first place.
- Some javadoc fixes while on it.

Async startup of the SSHD server

---

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

Amends #19 as per comments there.
@reviewbybees @olivergondza

SSHD startup should *not* be asynchronous

---

pom.xml

Pick new version of parent POM && Stop bundling the obsolete `slf4j-api`. `org.slf4j:slf4j-api:1.7.25` comes from the new SSHD core we bundle.
@reviewbybees

Update Plugin POM, resolve upper bounds

---

src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java

When using SSH to connect with CLI, we do not have event triggered by SecurityListener. With the proposed modifications, our listeners will also receive information when a user tried to authenticate (with success or not)
See [JENKINS-27026](https://issues.jenkins-ci.org/browse/JENKINS-27026).
* Fire security events when SSH transport is used for CLI authentication
* Use the `Internal: ` prefix if the change has no user-visible impact (API, test frameworks, etc.)
@reviewbybees

[JENKINS-27026] Fire authentication events when using SSH

---

pom.xml

Updated also instance-identity-module to solve a RequireUpperBoundDeps
issue when building with JDK 11 and Jenkins 2.161:
```
$ mvn -V -Djenkins.version=2.143 clean verify
...
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.jenkins-ci.modules:instance-identity:2.1 paths to dependency are:
+-org.jenkins-ci.modules:sshd:2.6-SNAPSHOT
+-org.jenkins-ci.modules:instance-identity:2.1
and
+-org.jenkins-ci.modules:sshd:2.6-SNAPSHOT
+-org.jenkins-ci.modules:ssh-cli-auth:1.4
+-org.jenkins-ci.modules:instance-identity:1.2
and
+-org.jenkins-ci.modules:sshd:2.6-SNAPSHOT
+-org.jenkins-ci.main:jenkins-war:2.143
+-org.jenkins-ci.modules:instance-identity:2.2
and
+-org.jenkins-ci.modules:sshd:2.6-SNAPSHOT …
```

Update to latest parent pom

---

src/main/java/org/jenkinsci/main/modules/sshd/IdleTimeout.java
src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
src/test/java/org/jenkinsci/main/modules/sshd/IdleTimeoutTest.java

https://github.com/jenkinsci/sshd-module/pull/6 is not enough, it only delays the timeout by 15 seconds.
Apache Mina's read timeout defaults to default idle timeout (10 minutes) + 15 seconds.
This PR makes sure read timeout follows idle timeout value.

[JENKINS-55978] - Apache Mina idle timeout configuration only delays the session timeout by 15 seconds

---

README.adoc
pom.xml
src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

By default, exclude SHA1 based key exchanges. Allow customizing which to exclude, and add logging to understand exactly what happens during filtering.
Exclusion of SHA1 based key exchanges has been implemented in newer versions of Mina according to https://github.com/apache/mina-sshd#implementedavailable-support but upgrading Mina seems like a bigger project (https://github.com/jenkinsci/sshd-module/pull/33). So choose this approach instead.
If this looks like a reasonable approach, we probably want to disable `hmac-md5`, `hmac-md5-96`, and `hmac-sha1-96` in a similar manner. They are also no longer available by default in Mina 2 (https://issues.apache.org/jira/browse/SSHD-1004).

Filter out SHA-1 key exchanges and MD5/truncated SHA-1 MACs

---

src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java
src/test/java/org/jenkinsci/main/modules/sshd/SSHDTest.java

This validates that a user logging in through SSH is not bypassing their SecurityRealm user validity attributes. This also updates user impersonation checks to use the core API.
It's an open question on how we'd like to expose a configuration option to admins to enable or disable this attribute check. I think it might make most sense to put the feature flags or config options in the SecurityRealm plugins themselves which can avoid setting dynamic values to those attributes.
https://issues.jenkins.io/browse/JENKINS-55813
This PR was originally part of https://github.com/jenkinsci/jenkins/pull/4925 which has been put aside in favor of directly patching the affected plugins. As such, I've added all the people who left comments on that PR as reviewers if any of you would like to take a look.

[JENKINS-55813] Ensure account status exceptions prevent successful SSH authentication

---

pom.xml
src/main/java/org/jenkinsci/main/modules/sshd/AsynchronousCommand.java
src/main/java/org/jenkinsci/main/modules/sshd/IdleTimeout.java
src/test/java/org/jenkinsci/main/modules/sshd/IdleTimeoutTest.java

see [JENKINS-60902](https://issues.jenkins-ci.org/browse/JENKINS-60902)
It bumps the [Apache Mina sshd](https://github.com/apache/mina-sshd) library to 2.7.0
it replaces https://github.com/jenkinsci/sshd-module/pull/33
it depends on [JENKINS-55582](https://issues.jenkins-ci.org/browse/JENKINS-55582)
This PR is the same change in https://github.com/jenkinsci/sshd-plugin/pull/37 but implement AsynchronousCommand as runnable due to some changes in the Apache Mina library, this requires changes on other plugins because of signature changes. The change is to rename the method `run` to `runCommand`.

Upgrade to SSHD 2.7.0

---

src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImpl.java
src/main/java/org/jenkinsci/main/modules/sshd/AsynchronousCommand.java
src/main/java/org/jenkinsci/main/modules/sshd/PortAdvertiser.java
src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java
src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

Removes JSR 305 and adds missing annotations.
There are still two types left:
- javax.annotation.CheckForSigned
- javax.annotation.concurrent.GuardedBy
Is there any suitable replacement?
/cc @basil
--------------------------------

Remove JSR 305

---

pom.xml

This plugin bundles `slf4j-api-1.7.36.jar` and `jcl-over-slf4j-1.7.36.jar`:
```
[INFO] Assembling webapp sshd in src/jenkinsci/sshd-plugin/target/sshd
[WARNING] Bundling transitive dependency self-signed-cert-generator-1.0.0.jar (via instance-identity)
[INFO] Bundling direct dependency eddsa-0.3.0.jar
[WARNING] Bundling transitive dependency sshd-common-2.8.0.jar (via sshd-core)
[INFO] Bundling direct dependency sshd-core-2.8.0.jar
[INFO] Bundling direct dependency instance-identity-2.2.jar
[WARNING] Bundling transitive dependency jcl-over-slf4j-1.7.36.jar (via sshd-core)
[WARNING] Bundling transitive dependency slf4j-api-1.7.36.jar (via sshd-core)
[INFO] Generating hpi src/jenkinsci/sshd-plugin/target/sshd.hpi
[INFO] Building jar: src/jenkinsci/sshd-plugin/target/sshd.hpi
```
This is …

Stop bundling SLF4J

---

.github/workflows/cd.yaml

See https://github.com/jenkinsci/jenkins/pull/6406 for more details
The 'adopt' distribution has moved to Eclipse Temurin and won't be updated at the AdoptOpenJDK location.  Switch to the Temurin distribution so that we use a current version of Java.
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~

Use Eclipse Temurin for action, not AdoptOpenJDK

---

pom.xml

#38 was incorrect. Noticed when trying to test https://github.com/jenkinsci/jenkins/pull/6585 that even when `instance-identity` is not enabled as a plugin, `InstanceIdentityRSAProvider` gets loaded from `plugins/sshd/WEB-INF/lib/instance-identity-2.2.jar`.

Do not bundle a copy of `instance-identity`

---

Jenkinsfile
pom.xml

Follows up #75. A release would be appreciated for BOM/PCT purposes. CC @kuisathaverat

Use `instance-identity` as a plugin rather than a module

---

pom.xml

Noticed that `/pluginManager/installed` showed this plugin without a hyperlink.

Forgotten `/project/url`

---

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java

No need to set the keyPairProvider to a default value then immediately set it to a different value.
Storing once should be enough.
Detect as the only production use of `SimpleGeneratorHostKeyProvider` in the Jenkins code base while investigating for https://github.com/jenkinsci/jenkins/pull/7623

Remove dead store to set the keyPairProvider

---

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java

Unused Java imports can be a distraction when reviewing changes.  Remove the unused imports.  Does not implement the automation to prevent future unused imports.
https://github.com/jenkinsci/sshd-plugin/pull/119#issuecomment-1449060893 is resolved by this change

Remove unused Java imports

---

pom.xml

Now that sshd is not in core and a plugin this dependency seems to be incorrect here, however I am making the most minimal changes for plugins to use the eddsa-api and am not investing time in checking the hypothesis.

replace eddsa dependency with eddsa-api plugin

---

src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImplTest.java

See https://github.com/jenkinsci/jenkins/pull/7268
Picked up in https://github.com/jenkinsci/bom/pull/3290/checks?check_run_id=25994358346
Tested locally with:
```
mvn test -Dtest=org.jenkinsci.main.modules.cli.auth.ssh.UserPropertyImplTest -Djenkins.version=2.462-rc35038.ce728646406e
```

Adapt tests to categorised user properties
