src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
[JENKINS-36420](https://issues.jenkins-ci.org/browse/JENKINS-36420)
Default value is 10min (like previously).  
System property to configure is `org.jenkinsci.main.modules.sshd.SSHD.idle-timeout` (value in milliseconds) 
Should replace #4 cc @reviewbybees @mplonka @oleg-nenashev @daniel-beck
=> [JENKINS-36420] Allow to configure the client idle timeout.

pom.xml, src/main/java/org/jenkinsci/main/modules/sshd/AsynchronousCommand.java, src/main/java/org/jenkinsci/main/modules/sshd/CLICommandAdapter.java, src/main/java/org/jenkinsci/main/modules/sshd/InvalidCommand.java, src/main/java/org/jenkinsci/main/modules/sshd/PortAdvertiser.java, src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java, src/main/java/org/jenkinsci/main/modules/sshd/SshCommandFactory.java, src/main/java/org/jenkinsci/main/modules/sshd/UserAuthNamedFactory.java, src/test/java/org/jenkinsci/main/modules/ssh/SSHDTest.java
@reviewbybees @jenkinsci/code-reviewers @aheritier
=> Update to the new Parent POM

Jenkinsfile
=> Add Jenkins file for builds on ci.jenkins.io

CHANGELOG.md
=> Changelog: Noting changes towards SSHD Module 2.0

pom.xml
Changelog: https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12341097&styleName=Text&projectId=12310849&Create=Create&atl_token=A5KQ-2QAV-T4JA-FDED%7C47f5fd1e799680219ff14477b5b2c29ce7aaf6fd%7Clin
I am not aware about any issues reported for Jenkins, but I have not deep dive into JIRA
@reviewbybees
=> Update SSHD Core to 1.7.0

pom.xml
=> JENKINS-45318 Add dependancy on net.i2p.crypto to Jenkins CLI

.mvn/extensions.xml, .mvn/maven.config, pom.xml
I used the easy, automated way to add incrementals support.
=> Enable incrementals.

pom.xml
Amends 7d8950a70393a4db1afc012305b2efc9c2d6e83d. This should be released ASAP I guess, and 3.0.2 bundled in core.
=> Use 2.282, not an incremental version

src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java
Amending #38 to focus on SSH-specific test scenarios.
=> Limiting CLITest to scenarios involving -ssh mode

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
Related to #50 and #49.
------------------------------------
=> Update @GuardedBy, remove @CheckForSigned

src/main/java/org/jenkinsci/main/modules/sshd/AsynchronousCommand.java, src/main/java/org/jenkinsci/main/modules/sshd/CLICommandAdapter.java, src/main/java/org/jenkinsci/main/modules/sshd/PortAdvertiser.java, src/main/java/org/jenkinsci/main/modules/sshd/UserAuthNamedFactory.java, src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java, src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImplTest.java
Remove some calls to deprecated APIs and use the mentioned replacements instead. There are acegi related deprecations left though.
Additionally, clean-up an unused import and simplify assertion.
----------------
=> Remove some deprecated API calls

src/main/java/org/jenkinsci/main/modules/sshd/CLICommandAdapter.java, src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java
[JENKINS-68541](https://issues.jenkins.io/browse/JENKINS-68541)
=> [JENKINS-68541] Prevent stdout/stderr stream from being closed by invoked CLI commands

pom.xml
[mina-sshd-api-plugin](https://github.com/jenkinsci/mina-sshd-api-plugin/) wraps the Apache MINA SSHD library as a plugin in Jenkins.
=> Bundle mina-sshd-api-core plugin instead of sshd-core

CHANGELOG.md, Jenkinsfile, README.adoc, src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java, src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java
=> module => plugin

pom.xml
Explicitly set the Mina SSHD plugin versions temporarily to fix PCT and BOM release:
* https://github.com/jenkinsci/bom/pull/2071
* https://github.com/jenkinsci/bom/pull/2083
cc @jglick @timja
=> Bump mina-sshd to 2.10.0-69.v28e3e36d18eb_

pom.xml
Follow up of https://github.com/jenkinsci/sshd-plugin/pull/142
=> Bump bom-2.361.x from 2081.v85885a_d2e5c5 to 2102.v854b_fec19c92

src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImpl.java
Depends on https://github.com/jenkinsci/jenkins/pull/7268 but can be released independently
=> Move ssh keys to security user page when available

src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java, src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/PublicKeySignatureWriterTest.java, src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImplTest.java, src/test/java/org/jenkinsci/main/modules/sshd/IdleTimeoutTest.java, src/test/java/org/jenkinsci/main/modules/sshd/SSHDTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5

pom.xml, src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/PublicKeySignatureWriter.java, src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImpl.java, src/main/java/org/jenkinsci/main/modules/sshd/PublicKeyAuthenticatorImpl.java, src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java, src/test/java/org/jenkinsci/main/modules/sshd/SSHDTest.java
Signed-off-by: Olivier Lamy <olamy@apache.org>
=> Fix support of EdDSA keys which was not working and use support of EdDSA natively provided now by Apache Mina via Bouncycastle

src/main/java/org/jenkinsci/main/modules/sshd/SSHD.java
Remove usages of Commons Lang 2
mvn clean install
=> Remove usages of Commons Lang 2
